name: Checks
on:
  push:
    branches:
      - main

jobs:
  checks-py-rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run Rust tests
        run: .venv/bin/activate && cargo test

      - name: Run Ruff
        run: uvx ruff check

      - name: Run Type Check
        run: uvx ty check

      - name: Run Python tests
        run: uv run pytest
